### ISSUE TITLE
init

### ISSUE THREAD

**Issue by Prudhvi0717** [maacarma/scheduler#1]
The high level tasks would be:

1. Cron (use exisiting cron library)
2.  API layer
3. Persistance
4. Infra Deployment

init tasks:

- [x] design the project structure - assignee @Prudhvi0717 
- [x] base API and repo layer - assignee @yashwanth-reddy909

**Comment by yashwanth-reddy909** [comment]
planned features and low level system design notes 

https://iron-box-a6c.notion.site/maacarma-scheduler-a31a1969d4bb4b7a99285cbd27d4e203

**Comment by Prudhvi0717** [comment]
This PR #5  marks the completion of init tasks planned.
Closing this issue.

Will update the follow up issue soon.
